name = "blog-iine"
compatibility_date = "2024-04-05"
compatibility_flags = [ "nodejs_compat" ]

pages_build_output_dir = ".vercel/output/static"

# [[d1_databases]]
# binding = "DB" # i.e. available in your Worker on env.DB
# database_name = "blog-iine-counter"
# database_id = "9b8830aa-c033-436e-8e32-ed7e3630af05"